delete from towns;
insert into towns (starts_with, town_name) values ('','Select Town');
insert into towns (starts_with, town_name) values ('all','All');
insert into towns (starts_with, town_name) values ('CA','Cape Town'); 
insert into towns (starts_with, town_name) values ('CAM','Caledon & Kleinmond');
insert into towns (starts_with, town_name) values ('CAR','Clanwilliam & Lamberts Bay');
insert into towns (starts_with, town_name) values ('CAW','George');
insert into towns (starts_with, town_name) values ('CBL','Ladismith');
insert into towns (starts_with, town_name) values ('CBM','Laingsburg');
insert into towns (starts_with, town_name) values ('CBR','Montagu');
insert into towns (starts_with, town_name) values ('CBS','Mossel Bay & Hartenbos');
insert into towns (starts_with, town_name) values ('CBT','Murraysburg');
insert into towns (starts_with, town_name) values ('CBY','Piketberg');
insert into towns (starts_with, town_name) values ('CCA','Prince Albert');
insert into towns (starts_with, town_name) values ('CCC','Riversdale & Still Bay');
insert into towns (starts_with, town_name) values ('CCD','Robertson & McGregor');
insert into towns (starts_with, town_name) values ('CCK','Swellendam & Barrydale');
insert into towns (starts_with, town_name) values ('CCM','Tulbagh');
insert into towns (starts_with, town_name) values ('CCO','Uniondale');
insert into towns (starts_with, town_name) values ('CCP','Vanrhynsdorp & Klawer');
insert into towns (starts_with, town_name) values ('CEA','Moorreesburg');
insert into towns (starts_with, town_name) values ('CEG','Heidelberg');
insert into towns (starts_with, town_name) values ('CEM','Hermanus, Gans Bay, Onrus River & Stanford');
insert into towns (starts_with, town_name) values ('CEO','Grabouw');
insert into towns (starts_with, town_name) values ('CER','Bonnievale');
insert into towns (starts_with, town_name) values ('CES','Albertinia');
insert into towns (starts_with, town_name) values ('CEX','Porterville');
insert into towns (starts_with, town_name) values ('CEY','Strand & Gordons Bay');
insert into towns (starts_with, town_name) values ('CFA','Wolseley');
insert into towns (starts_with, town_name) values ('CFG','Vredenburg & St Helena Bay');
insert into towns (starts_with, town_name) values ('CFM','Somerset West');
insert into towns (starts_with, town_name) values ('CFP','Velddrif');
insert into towns (starts_with, town_name) values ('CFR','Kuilsrivier & Brackenfell');
insert into towns (starts_with, town_name) values ('CG','Oudtshoorn');
insert into towns (starts_with, town_name) values ('CJ','Paarl & Franschhoek');
insert into towns (starts_with, town_name) values ('CK','Malmesbury & Darling');
insert into towns (starts_with, town_name) values ('CL','Stellenbosch');
insert into towns (starts_with, town_name) values ('CN','Wellington');
insert into towns (starts_with, town_name) values ('CO','Calitzdorp');
insert into towns (starts_with, town_name) values ('CR','Hopefield & Langebaan');
insert into towns (starts_with, town_name) values ('CS','Bredasdorp & Napier');
insert into towns (starts_with, town_name) values ('CT','Ceres');
insert into towns (starts_with, town_name) values ('CV','Vredendal');
insert into towns (starts_with, town_name) values ('CW','Worcester, De Doorns & Touwsrivier');
insert into towns (starts_with, town_name) values ('CX','Knysna, Sedgefield & Plettenberg Bay');
insert into towns (starts_with, town_name) values ('CY','Bellville, Durbanville & Kraaifontein');
insert into towns (starts_with, town_name) values ('CZ','Beaufort West');
